### ISSUE TITLE
ENV file using react-native-config

### ISSUE THREAD

**Issue by audywp** [warungpintar/renceng-native#25]
untuk beberapa variable sensitif untuk sementara di hardcode, next mungkin bisa pindah ke react native config

list hardcoded variable : 

- IMAGEPROXY_KEY
- IMAGEPROXY_SALT
- IMAGEPROXY_HOST

**Comment by andhikaribrahim** [comment]
Closing issue as per our discussion, `.env` file shouldn't be in our DLS repo
