### ISSUE TITLE
Button component issues

### ISSUE THREAD

**Issue by irxd** [warungpintar/renceng-native#40]
- button name not working
- button name not centered
- missing size xs
- need color props
- need text props

**Comment by andhikaribrahim** [comment]
@irxd size xs ini spec nya bisa gue liat dimana ya sad?

**Comment by irxd** [comment]
@andhikaribrahim yang xs ini mesti liat di dls warungpintar/ui

ini case buat compatibilty aja sih buat migrate nanti, soalnya beberapa gw cek kemaren ada yang pake xs
gw belom ngecek pastinya si xs berapa sih, ntar sekalian cek aja

**Comment by irxd** [comment]
resolved with https://github.com/warungpintar/renceng-native/pull/46
